export const formData = [
  {
    id: 0,
    titulo: "Por favor indique la presencia de las siguientes canastas:",
    respuesta_correcta: "París",
    arrayRespuestas: ["Alimentos", "Aseo del hogar", "Aseo Personal", "Bebidas no Alcocholicas", "Confiteria", "Licores y Tabacos", "Medicinal", "Miscelaneos", "Mascotas"],
    tipo: "multiseleccion",
    segmento: "Grupo Z",
  },
  {
    id: 1,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA ALIMENTOS en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "ARROZ",
    arrayRespuestas: ["ACEITES LIQUIDOS", "AREPAS LISTAS", "ARROZ", "GRANOS CRUDOS", "ATUN", "AVENAS LIQUIDAS", "AZUCAR", "BEBIDAS LACTEAS", "CAFE", "CALDOS CONCENTRADOS", "CARNE FRESCA", "CARNES FRIAS", "CERALES LISTOS", "CERALES PROCESADOS", "CHOCOLATE DE MESA", "COMPOTAS", "CONDIMENTOS", "CREMA DE LECHE", "GRANOLAS", "HARINAS MAIZ PRECOCIDAS", "HARINAS TRIGO", "HUEVOS", "INFUSIONES", "LECHE EN POLVO", "LECHE LIQUIDA", "LECHE SABORIZADA", "MARGARINAS INDUSTRIALES", "MANTEQUILLAS", "MAYONESA", "MODIFICADORES DE LECHE"],
    tipo: "multiseleccion",
    segmento: "alimentos",
  },
  {
    id: 2,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA ASEO DEL HOGAR en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "AMBIENTADORES",
    arrayRespuestas: ["AMBIENTADORES", "BLANQUEADORES", "DESMANCHADOR", "DETERGENTE DE ROPA", "LAVALOZA", "ESPONJILLAS", "JABONES EN BARRA", "LIMPIADORES", "SERVILLETAS", "SUAVISANTES", "TOALLAS DE COCINA"],
    tipo: "multiseleccion",
    segmento: "hogar",
  },
  {
    id: 3,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA ASEO PERSONAL en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "BLOQUEADOR",
    arrayRespuestas: ["ACONDICIONADOR BALSAMOS", "BLOQUEADOR", "BRONCEADOR", "CEPILLOS DENTALES", "CREMA DE AFEITAR", "CREMA DENTRAL", "CREMA PARA MANOS Y CUERPO", "CREMA PARA PEINAR", "DESODORANTE PARA PIE", "DESODORANTES CORPORALES", "ENJUAGUE BUCAL", "JABON DE TOCADOR", "MAQUINAS REPUESTOS Y CUCHILLAS", "PANALES PARA ADULTOS", "PANALES PARA BEBE", "PANITOS HUMEDOS", "PAPEL HIGIENICO", "PANUELOS DESECHABLES", "PROTECCION FEMENINA", "SHAMPOO", "TRATAMIENTO CAPILAR"],
    tipo: "multiseleccion",
    segmento: "personal",
  },
  {
    id: 4,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA DE BEBIDAS NO ALCOHOLICAS en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "GASEOSAS",
    arrayRespuestas: ["BEBIDAS EN POLVO", "AGUA CON MARCA", "ENERGIZANTES", "ISOTONICAS (HIDRATANTES)", "GASEOSAS", "JUEGO", "MALTAS", "TE LIQUIDO"],
    tipo: "multiseleccion",
    segmento: "no alcohol",
  },
  {
    id: 41,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA DE COFITERIA en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "AREQUIPE",
    arrayRespuestas: ["AREQUIPE", "CEREALES EN BARRA", "CHICLES", "DULCE DE CHOCOLATE", "DULCES", "FRUTOS SECOS", "GALLETAS", "GELATINAS EN POLVO", "HELADOS CON MARCA", "LECHE CONDENSADA", "PASABOCAS", "PONQUES Y BROWNIES", "POSTRES LISTOS"],
    tipo: "multiseleccion",
    segmento: "cofiteria",
  },
  {
    id: 42,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA DE LICORES Y TABACOS en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "AGUARDIENTE",
    arrayRespuestas: ["AGUARDIENTE", "APERITIVO", "BRANDY", "CERVEZA", "CIGARRILLOS", "CREMA DE LICORES", "GINEBRA", "RON", "TEQUILA", "VINO ESPUMOSO", "VINOS", "VODKA", "WHISKY", "RTD ALCOHOLICAS", "VAPEADORES"],
    tipo: "multiseleccion",
    segmento: "alcohol",
  },
  {
    id: 43,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA MASCOTAS en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "ALIMENTOS PARA GATOS",
    arrayRespuestas: ["ACCESORIOS PARA MASCOTAS", "ALIMENTO PARA ANIMALES DE CAMPO", "ALIMENTOS PARA GATOS", "ALIMENTOS PARA OTRAS MASCOTAS", "ALIMENTOS PARA PERROS", "ARENA PARA GATOS", "BANO SECO PARA ANIMALES"],
    tipo: "multiseleccion",
    segmento: "mascotas",
  },
  {
    id: 44,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA MISCELANEOS en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "BOMBILLOS",
    arrayRespuestas: ["BOMBILLOS", "CONDONES", "PRODUCTOS DESECHABLES", "EMPAQUES DE CONSEVACION", "ENCEDEDORES", "PILAS"],
    tipo: "multiseleccion",
    segmento: "miscelaneos",
  },
  {
    id: 45,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA MEDICINAL en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "ALCOHOL",
    arrayRespuestas: ["ADHESIVOS DE PROTESIS", "ALCOHOL", "ALGODON", "ANALGESICOS", "ANTIACIDOS", "ANTIGRIPALES", "ANTIMICOTICO", "COMPLEMENTOS ALIMENTICIOS", "COPITOS", "CURAS", "FORMULAS INFANTILES", "GASA", "LAXANTES", "LOCION MENTOLADA", "MICROPORE", "REPELENTE", "SUEROS DE HIDRATACION"],
    tipo: "multiseleccion",
    segmento: "medicinal",
  },
  {
    id: 5,
    titulo: "¿Hay equipo de enfriamientio?",
    respuesta_correcta: "SI",
    arrayRespuestas: ["SI", "NO"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 6,
    titulo: "¿Hay equipos de enfriamientio No patrocinados en el establecimiento?",
    respuesta_correcta: "SI",
    arrayRespuestas: ["SI", "NO"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 7,
    titulo: "Seleccione el número de NEVERAS que se encuentran PATROCINADAS por las siguientes marcas:",
    respuesta_correcta: "Postobón",
    arrayRespuestas: ["Postobón", "Coca Cola", "Aje", "Quala(Vive100,Saviloe)", "Alpina", "Bavaria", "Pony Malta"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 8,
    titulo: "Coca Cola Nevera (*Está conectada?)",
    respuesta_correcta: "SI",
    arrayRespuestas: ["SI", "NO"],
    tipo: "multiseleccion",
    segmento: "cocacola",
  },
  {
    id: 9,
    titulo: "Coca Cola Nevera (*La Nevera Coca Cola)",
    respuesta_correcta: "Sirve",
    arrayRespuestas: ["Sirve", "No Sirve"],
    tipo: "multiseleccion",
    segmento: "cocacola",
  },
  {
    id: 10,
    titulo: "Coca Cola Nevera (*La Nevera Coca Cola)",
    respuesta_correcta: "Sirve",
    arrayRespuestas: ["Sirve", "No Sirve"],
    tipo: "multiseleccion",
    segmento: "cocacola",
  },
  {
    id: 11,
    titulo: "Coca Cola Nevera (*Se respeta el bloque de Colas Negras)",
    respuesta_correcta: "Si",
    arrayRespuestas: ["Si", "No"],
    tipo: "multiseleccion",
    segmento: "cocacola",
  },
  {
    id: 12,
    titulo: "Coca Cola Nevera (*Se respeta el bloque de resto de bloque de sabores?)",
    respuesta_correcta: "Si",
    arrayRespuestas: ["Si", "No"],
    tipo: "multiseleccion",
    segmento: "cocacola",
  },
  {
    id: 13,
    titulo: "Coca Cola Nevera (*Invadida x Competencia)",
    respuesta_correcta: "Si",
    arrayRespuestas: ["Si", "No"],
    tipo: "multiseleccion",
    segmento: "cocacola",
  },
  {
    id: 14,
    titulo: "Coca Cola Nevera (*Invadida x otros Productos)",
    respuesta_correcta: "Si",
    arrayRespuestas: ["Si", "No"],
    tipo: "multiseleccion",
    segmento: "cocacola",
  },
  {
    id: 15,
    titulo: "Coca Cola Nevera ( *Indique el porcentaje de llenado de Nevera Coca Cola)",
    respuesta_correcta: "Si",
    arrayRespuestas: ["0-25%", "26-50%", "51-75%", "mas del 75%", "Vacia"],
    tipo: "multiseleccion",
    segmento: "cocacola",
  },
  {
    id: 16,
    titulo: "Coca Cola Nevera ( *Indique el porcentaje de llenado de Nevera Coca Cola)",
    respuesta_correcta: "Si",
    arrayRespuestas: ["0-25%", "26-50%", "51-75%", "mas del 75%", "Vacia"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 17,
    titulo: "Coca Cola Nevera ( *Numero de Puertas)",
    respuesta_correcta: "1",
    arrayRespuestas: ["1", "2", "3", "4"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 18,
    titulo: "Que tipos de Equipos de Enfriamiento PATROCINADOS:",
    respuesta_correcta: "Nevera",
    arrayRespuestas: ["Nevera", "Botellero", "Mostrador", "Congelador"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 19,
    titulo: "Fotos Equipos (* Foto Nevera Patrocinada Coca Cola)",
    respuesta_correcta: "imgCigarros",
    arrayRespuestas: ["imgCigarros"],
    tipo: "foto",
    segmento: "Img_Coca_Cola",
  },
  {
    id: 199,
    titulo: "Capturar fotografia General del Punto de venta 1",
    respuesta_correcta: "imgCigarrillos",
    arrayRespuestas: ["imgCigarrillos"],
    tipo: "foto",
    segmento: "img_cigarrillos",
  },
  {
    id: 1999,
    titulo: "Capture foto de la exhibicion de analgesicos, si no hay exhibicion pida al tendero que le deje tomar foto a donde almacena los analgesicos Tomar la foto al lado de la caja del establecimiento",
    respuesta_correcta: "imgMedicamento",
    arrayRespuestas: ["imgMedicamento"],
    tipo: "foto",
    segmento: "img_medicamentos",
  },
  {
    id: 453634,
    titulo: "Capturar una foto donde se visualice la seccion de aseo hogar en el establecimiento",
    respuesta_correcta: "imgPapel",
    arrayRespuestas: ["imgPapel"],
    tipo: "foto",
    segmento: "Img_aseo_personal",
  },
  {
    id: 54634,
    titulo: "Fotos Equipos (* Foto Nevera Patrocinada Postobon)",
    respuesta_correcta: "imgPostobon",
    arrayRespuestas: ["imgPostobon"],
    tipo: "foto",
    segmento: "Img_postobon",
  },
  {
    id: 20,
    titulo: "Marque la presencia de las siguientes Marcas de Aguas (FEMSA)",
    respuesta_correcta: "Brisa",
    arrayRespuestas: ["Brisa", "Manantial", "Tai", "No hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 21,
    titulo: "Marque la presencia de las siguientes Marcas de Aguas (POSTOBON)",
    respuesta_correcta: "Acqua",
    arrayRespuestas: ["Acqua", "Cristal", "Cristalina", "H2Oh", "Hatsu", "No hay"],
    tipo: "multiseleccion",
    segmento: "postobon",
  },
  {
    id: 22,
    titulo: "Marque la presencia de las siguientes Marcas de Aguas (POSTOBON)",
    respuesta_correcta: "Acqua",
    arrayRespuestas: ["Acqua", "Cristal", "Cristalina", "H2Oh", "Hatsu", "No hay"],
    tipo: "multiseleccion",
    segmento: "postobon",
  },
  {
    id: 23,
    titulo: "Marque la presencia de las siguientes Marcas de Energizante (FEMSA)",
    respuesta_correcta: "Acqua",
    arrayRespuestas: ["Monster", "No hay",],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 24,
    titulo: "Marque la presencia de las siguientes Marcas de Energizante (POSTOBON)",
    respuesta_correcta: "Peak",
    arrayRespuestas: ["Peak", "Red Bull", "Speed Max", "No hay"],
    tipo: "multiseleccion",
    segmento: "postobon",
  },
  {
    id: 25,
    titulo: "Marque la presencia de las siguientes Marcas de Gaseosas (FEMSA)",
    respuesta_correcta: "Quatro",
    arrayRespuestas: ["Coca Cola", "Coca Cola Con Cafe", "Fanta", "Kola Roman", "Premio", "Quatro", "Schweppes", "Sprite", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 26,
    titulo: "Marque la presencia de las siguientes Marcas de Gaseosas (POSTOBON)",
    respuesta_correcta: "7Up",
    arrayRespuestas: ["7Up", "Bretana", "Canada Dry", "Colombiana", "Freskola", "Hipinto", "Kola", "Limonada Postobon", "Manzana Postobon", "Naranja Postobon"],
    tipo: "multiseleccion",
    segmento: "postobon",
  },
  {
    id: 27,
    titulo: "Marque la presencia de las siguientes Marcas de Hidratante (FEMSA)",
    respuesta_correcta: "Powerade",
    arrayRespuestas: ["Powerade", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 28,
    titulo: "Marque la presencia de las siguientes Marcas de Hidratante (POSTOBON)",
    respuesta_correcta: "Gatorade",
    arrayRespuestas: ["Gatorade", "Squash", "No Hay"],
    tipo: "multiseleccion",
    segmento: "postobon",
  },
  {
    id: 29,
    titulo: "Marque la presencia de las siguientes Marcas de Jugos (FEMSA)",
    respuesta_correcta: "Ades",
    arrayRespuestas: ["Ades", "Del Valle Frutal", "Del Valle Fresh"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 30,
    titulo: "Marque la presencia de las siguientes Marcas de Jugos (POSTOBON)",
    respuesta_correcta: "Hit",
    arrayRespuestas: ["Hit", "Tutti Frutti", "Tutti Frutti Citrico/Salpicon", "No Hay"],
    tipo: "multiseleccion",
    segmento: "postobon",
  },
  {
    id: 31,
    titulo: "Marque la presencia de las siguientes Marcas de Maltas",
    respuesta_correcta: "Hit",
    arrayRespuestas: ["Malta Leona", "Natu Malta", "Pony Malta", "Pony Malta Vital", "Otras Marcas Maltas", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 32,
    titulo: "Marque la presencia de las siguientes Marcas de Agua: (OTRAS MARCAS)",
    respuesta_correcta: "Cielo",
    arrayRespuestas: ["Agua de Oro", "Cielo", "Condor", "Glacial", "Pool", "Saviloe", "Disfruta Aloe", "Nevada", "Vida", "Zen"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 33,
    titulo: "Marque la presencia de las siguientes Marcas de Energizante (OTRAS MARCAS)",
    respuesta_correcta: "Cielo",
    arrayRespuestas: ["Amper", "Vive 100%", "Spartan", "Energy Pool", "Full Energy Plus", "Volt", "Otras Marcas", "No hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 34,
    titulo: "Marque la presencia de las siguientes Marcas de Hidratante (OTRAS MARCAS)",
    respuesta_correcta: "Sporade",
    arrayRespuestas: ["Sporade", "Sport Mas", "Fullpower", "Hydratade Pool", "Otras Marcas", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 35,
    titulo: "Marque la presencia de las siguientes Marcas de Jugos (OTRAS MARCAS)",
    respuesta_correcta: "Cifrut",
    arrayRespuestas: ["Cifrut", "Pulp", "Fruper", "Frutto", "Sip", "Soka", "Noectar Petit", "Fruttsi", "California", "California Fesky"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 36,
    titulo: "Marque la presencia de las siguientes Marcas de Te Liquido (FEMSA)",
    respuesta_correcta: "Fuze Tea",
    arrayRespuestas: ["Fuze Tea", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 37,
    titulo: "Marque la presencia de las siguientes Marcas de Te Liquido",
    respuesta_correcta: "Cool Tea",
    arrayRespuestas: ["Cool Tea", "Otras Marcas", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 38,
    titulo: "Marque la presencia de las siguientes Marcas de Te Liquido (Postobon)",
    respuesta_correcta: "Hatsu",
    arrayRespuestas: ["Hatsu", "Lipton", "Mr Tea", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 39,
    titulo: "Marque la presencia de las siguientes Marcas de Gaseosas: (OTRAS MARCAS)",
    respuesta_correcta: "Pool",
    arrayRespuestas: ["Big Cola", "Big Festival", "Big otros Sabores", "Glacial", "Frizz", "Pool", "Otras Marcas", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 41,
    titulo: "Postobon Nevera (Está conectada?)",
    respuesta_correcta: "SI",
    arrayRespuestas: ["SI", "NO"],
    tipo: "multiseleccion",
    segmento: "cocacola",
  },
  {
    id: 42,
    titulo: "Postobon Nevera (* La nevera de Postobon es..?)",
    respuesta_correcta: "Pool",
    arrayRespuestas: ["Propia del fabricante", "Propia del tendero pero está brandeada con marcas Postobon"],
    tipo: "multiseleccion",
    segmento: "postobon",
  },
  {
    id: 43,
    titulo: "Postobon Nevera (Invadida x competencia)",
    respuesta_correcta: "Pool",
    arrayRespuestas: ["SI", "NO"],
    tipo: "multiseleccion",
    segmento: "postobon",
  },
  {
    id: 44,
    titulo: "Postobon Nevera (Invadida x otros productos)",
    respuesta_correcta: "SI",
    arrayRespuestas: ["SI", "NO"],
    tipo: "multiseleccion",
    segmento: "postobon",
  },
  {
    id: 45,
    titulo: "Postobon Nevera (Invadida x Licores)",
    respuesta_correcta: "SI",
    arrayRespuestas: ["SI", "NO"],
    tipo: "multiseleccion",
    segmento: "postobon",
  },
  {
    id: 46,
    titulo: "Coca Cola Nevera ( *Indique el porcentaje de llenado de Nevera Postobon)",
    respuesta_correcta: "0-25%",
    arrayRespuestas: ["0-25%", "26-50%", "51-75%", "mas del 75%", "Vacia"],
    tipo: "multiseleccion",
    segmento: "postobon",
  },
  {
    id: 47,
    titulo: "Marque la presencia de las siguientes bebidas lacteas del fabricante Alpina (Yogurt Kumis)",
    respuesta_correcta: "0-25%",
    arrayRespuestas: ["Alpina Deslactosado Yogurt Botella Familiar", "Alpina Deslactosado Yogurt Bolsa Familiar","Alpina Deslactosado Yogurt Vaso", "Alpina kumis Bolsa Familiar", "Alpina Kumis Bolsa Personal", "Alpina Kumis Botella Familiar", "Alpina Kumis Vaso", "Alpina Yogurt Vaso", "Alpina Yogurt Botella Familiar", "Alpina Griego Yogurt Vaso", "Finesse Griego Yogurt Vaso", "Finesse Yogurt Botella Familiar", "Regeneris Yogurt (Vaso) Personal", "Regeneris Yogurt Botella Familiar", "Yogo Yogo (Vaso)", "Yogo Yogo Cuchareable Yogurt (Vaso)", "Yogo Yogo (Vaso)", "Yogo Yogo Premio Yogurt Botella Personal", "Yogo Yogo Premio Bolsa Familia", "Yogo Yogo Yogurt Bolsa Personal", "Yogo Yogo Yogurt Tetrapack", "Yox Defensis Yogurt Botella Personal", "Yogo Yogo Fresh Yogurt Botella Personal", "Yogurt Original Fresa Vaso"],
    tipo: "multiseleccion",
    segmento: "no alcohol",
  },
  {
    id: 48,
    titulo: "Presencia (* Marque la presencia de las siguientes marcas de Papel Higienico)",
    respuesta_correcta: "Elite",
    arrayRespuestas: ["Elite", "Familia", "Joya", "Kleenex", "Nube", "Rendy", "Rosal", "Scott", "Sedamax", ""],
    tipo: "multiseleccion",
    segmento: "personal",
  },
  {
    id: 49,
    titulo: "Ingresa las marcas que encuentra de protección femenina",
    respuesta_correcta: "Elite",
    arrayRespuestas: ["Carefree", "Kotex", "Nosotras", "Fresh & Free", "Otras Marcas", "No hay"],
    tipo: "multiseleccion",
    segmento: "personal",
  },
  {
    id: 50,
    titulo: "Pregunte al tendero que marcas maneja de la categoria cigarrillos",
    respuesta_correcta: "Elite",
    arrayRespuestas: ["Blends", "Camel", "Caribe", "Chesterfield", "Heets", "L&M", "Lucky Strike (Kool)", "Malboro", "Piel roja", "President", "Rothmans (Mustang)", "Starlite", "Winston", "Otras marcas", "No hay"],
    tipo: "multiseleccion",
    segmento: "alcohol",
  },
  {
    id: 51,
    titulo: "Presencias Cerveza(*Marque la presencia de las siguientes marcas de Cervezas",
    respuesta_correcta: "Elite",
    arrayRespuestas: ["Costeña", "Costeñita", "Costeña Bacana", "Aguila Cero", "Aguila Original", "Aguila Light", "Budweiser", "Buckler", "Becks", "Club Colombia Dorada", "Club Colombia Negra", "Club Colombia Roja", "Club Colombia Trigo", "Corona Extra", "Coronita", "Heiniken", "Heiniken 0.0", "Miller Lite", "Michelob ultra"],
    tipo: "multiseleccion",
    segmento: "cervezas",
  },
  {
    id: 52,
    titulo: "Marque la presencia observadas de las siguientes marcas de aguardiente",
    respuesta_correcta: "Elite",
    arrayRespuestas: ["Amarillo de manzanares", "Antioqueño", "Cristal", "Nectar", "Otras Marcas", "No hay"],
    tipo: "multiseleccion",
    segmento: "alcohol",
  },
  {
    id: 52,
    titulo: "Marque la presencia observadas de las siguientes marcas de Ron",
    respuesta_correcta: "Elite",
    arrayRespuestas: ["Appleton State", "Bardi", "Havana Club", "Malibu", "Ron Medellin", "Ron viejo Caldas", "Ron Santa Fe", "Ron Barcelo", "Ron Zacapa", "Sailo Jerry"],
    tipo: "multiseleccion",
    segmento: "alcohol",
  },
  {
    id: 52,
    titulo: "Marque la presencia de las siguientes marcas de Whiskey",
    respuesta_correcta: "Elite",
    arrayRespuestas: ["Ballantines", "Black & White", "Buchanas", "Chivas Regal", "Dewars", "Glenfiddich", "Glenlivet", "Glenmorangie", "Grants", "Jack Daniels", "Jameson", "Jhonnie Walker", "Old Parr", "Passport Scotch", "Sigleton", "Something Special", "The famous grouse", "Tullamore Dew", "Vat 69", "William Lausons", "Otras Marcas"],
    tipo: "multiseleccion",
    segmento: "alcohol",
  },
];
