export const formData = [
  {
    id: 0,
    titulo: "Por favor indique la presencia de las siguientes canastas:",
    respuesta_correcta: "París",
    arrayRespuestas: ["Alimentos", "Aseo del hogar", "Aseo Personal", "Bebidas no Alcocholicas", "Confiteria", "Licores y Tabacos", "Medicinal", "Miscelaneos", "Mascotas"],
    tipo: "multiseleccion",
    segmento: "Grupo Z",
  },
  {
    id: 1,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA ALIMENTOS en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "Amazonas",
    arrayRespuestas: ["ACEITES LIQUIDOS", "AREPAS LISTAS", "ARROZ", "GRANOS CRUDOS", "ATUN", "AVENAS LIQUIDAS", "AZUCAR", "BEBIDAS LACTEAS", "CAFE"],
    tipo: "multiseleccion",
    segmento: "Grupo A",
  },
  {
    id: 2,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA ASEO DEL HOGAR en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "AMBIENTADORES",
    arrayRespuestas: ["AMBIENTADORES", "BLANQUEADORES", "DESMANCHADORES", "DETERGENTE DE ROPA", "LAVALOZA", "ESPONJILLAS", "JABONES EN BARRA", "LIMPIADORES", "SERVILLETAS"],
    tipo: "multiseleccion",
    segmento: "Grupo A",
  },
  {
    id: 3,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA ASEO PERSONAL en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "BLOQUEADOR",
    arrayRespuestas: ["ACONDICIONADOR BALSAMOS", "BLOQUEADOR", "BRONCEADOR", "CEPILLOS DENTALES", "CREMA DE AFEITAR", "CREMA DENTRAL", "CREMA PARA MANOS Y CUERPO", "CREMA PARA PEINAR", "DESODORANTE PARA PIE"],
    tipo: "multiseleccion",
    segmento: "Grupo A",
  },
  {
    id: 4,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA DE BEBIDAS NO ALCOHOLICAS en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "GASEOSAS",
    arrayRespuestas: ["BEBIDAS EN POLVO", "AGUA CON MARCA", "ENERGIZANTES", "ISOTONICAS (HIDRATANTES)", "GASEOSAS", "JUEGO", "MALTAS", "TE LIQUIDO"],
    tipo: "multiseleccion",
    segmento: "Grupo A",
  },
  {
    id: 41,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA DE COFITERIA en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "AREQUIPE",
    arrayRespuestas: ["AREQUIPE", "CEREALES EN BARRA", "CHICLES", "DULCE DE CHOCOLATE", "DULCES", "FRUTOS SECOS", "GALLETAS", "GELATINAS EN POLVO", "HELADOS CON MARCA"],
    tipo: "multiseleccion",
    segmento: "Grupo A",
  },
  {
    id: 42,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA DE LICORES Y TABACOS en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "AGUARDIENTE",
    arrayRespuestas: ["AGUARDIENTE", "APERITIVO", "BRANDY", "CERVEZA", "CIGARRILLOS", "CREMA DE LICORES", "GINEBRA", "RON", "TEQUILA"],
    tipo: "multiseleccion",
    segmento: "Grupo A",
  },
  {
    id: 43,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA MASCOTAS en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "ALIMENTOS PARA GATOS",
    arrayRespuestas: ["ACCESORIOS PARA MASCOTAS", "ALIMENTO PARA ANIMALES DE CAMPO", "ALIMENTOS PARA GATOS", "ALIMENTOS PARA OTRAS MASCOTAS", "ALIMENTOS PARA PERROS", "ARENA PARA GATOS", "BANO PARA ANIMALES", "CREMA DENTAL"],
    tipo: "multiseleccion",
    segmento: "Grupo A",
  },
  {
    id: 44,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA MISCELANEOS en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "BOMBILLOS",
    arrayRespuestas: ["BOMBILLOS", "CONDONES", "PRODUCTOS DESECHABLES", "EMPAQUES DE CONSEVACION", "ENCEDEDORES", "PILAS"],
    tipo: "multiseleccion",
    segmento: "Grupo A",
  },
  {
    id: 45,
    titulo: "!!ATENCION!! Observe con detenimiento las categorías de la CANASTA MEDICINAL en el establecimiento y selecciónelas de la lista:",
    respuesta_correcta: "BOMBILLOS",
    arrayRespuestas: ["ADHESIVOS DE PROTESIS", "ALCOHOL", "ALGODON", "ANALGESICOS", "ANTIACIDOS", "ANTIGRIPALES", "ANTIMICOTICO", "COMPLEMENTOS ALIMENTICIOS", "COPITOS"],
    tipo: "multiseleccion",
    segmento: "Grupo A",
  },
  {
    id: 5,
    titulo: "¿Hay equipo de enfriamientio?",
    respuesta_correcta: "SI",
    arrayRespuestas: ["SI", "NO"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 6,
    titulo: "¿Hay equipo de enfriamientio patrocinados en el establecimiento?",
    respuesta_correcta: "SI",
    arrayRespuestas: ["SI", "NO"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 7,
    titulo: "Seleccione el número de NEVERAS que se encuentran PATROCINADAS por las siguientes marcas:",
    respuesta_correcta: "Postobón",
    arrayRespuestas: ["Postobón", "Coca Cola", "Aje", "Quala(Vive100,Saviloe)", "Alpina", "Bavaria", "Pony Malta"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 8,
    titulo: "Coca Cola Nevera (*Está conectada?)",
    respuesta_correcta: "Postobón",
    arrayRespuestas: ["SI", "NO"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 9,
    titulo: "Coca Cola Nevera (*La Nevera Coca Cola)",
    respuesta_correcta: "Sirve",
    arrayRespuestas: ["Sirve", "No Sirve"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 10,
    titulo: "Coca Cola Nevera (*La Nevera Coca Cola)",
    respuesta_correcta: "Sirve",
    arrayRespuestas: ["Sirve", "No Sirve"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 11,
    titulo: "Coca Cola Nevera (*Se respeta el bloque de Colas Negras)",
    respuesta_correcta: "Si",
    arrayRespuestas: ["Si", "No"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 12,
    titulo: "Coca Cola Nevera (*Se respeta el bloque de resto de bloque de sabores?)",
    respuesta_correcta: "Si",
    arrayRespuestas: ["Si", "No"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 13,
    titulo: "Coca Cola Nevera (*Invadida x Competencia)",
    respuesta_correcta: "Si",
    arrayRespuestas: ["Si", "No"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 14,
    titulo: "Coca Cola Nevera (*Invadida x otros Productos)",
    respuesta_correcta: "Si",
    arrayRespuestas: ["Si", "No"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 15,
    titulo: "Coca Cola Nevera ( *Indique el porcentaje de llenado de Nevera Coca Cola)",
    respuesta_correcta: "Si",
    arrayRespuestas: ["0-25%", "26-50%", "51-75%", "mas del 75%", "Vacia"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 16,
    titulo: "Coca Cola Nevera ( *Indique el porcentaje de llenado de Nevera Coca Cola)",
    respuesta_correcta: "Si",
    arrayRespuestas: ["0-25%", "26-50%", "51-75%", "mas del 75%", "Vacia"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 17,
    titulo: "Coca Cola Nevera ( *Numero de Puertas)",
    respuesta_correcta: "1",
    arrayRespuestas: ["1", "2", "3", "4"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 18,
    titulo: "Que tipos de Equipos de Enfriamiento PATROCINADOS:",
    respuesta_correcta: "Nevera",
    arrayRespuestas: ["Nevera", "Botellero", "Mostrador", "Congelador"],
    tipo: "multiseleccion",
    segmento: "Neveras",
  },
  {
    id: 19,
    titulo: "Fotos Equipos (* Foto Nevera Patrocinada Coca Cola)",
    respuesta_correcta: "imgCoca",
    arrayRespuestas: ["imgCoca"],
    tipo: "foto",
    segmento: "Img_Coca_Cola",
  },
  {
    id: 20,
    titulo: "Marque la presencia de las siguientes Marcas de Aguas (FEMSA)",
    respuesta_correcta: "Brisa",
    arrayRespuestas: ["Brisa", "Manantial", "Tai", "No hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 21,
    titulo: "Marque la presencia de las siguientes Marcas de Aguas (POSTOBON)",
    respuesta_correcta: "Acqua",
    arrayRespuestas: ["Acqua", "Cristal", "Cristalina", "H2Oh", "Hatsu", "No hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 22,
    titulo: "Marque la presencia de las siguientes Marcas de Aguas (POSTOBON)",
    respuesta_correcta: "Acqua",
    arrayRespuestas: ["Acqua", "Cristal", "Cristalina", "H2Oh", "Hatsu", "No hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 23,
    titulo: "Marque la presencia de las siguientes Marcas de Energizante (FEMSA)",
    respuesta_correcta: "Acqua",
    arrayRespuestas: ["Monster", "No hay",],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 24,
    titulo: "Marque la presencia de las siguientes Marcas de Energizante (POSTOBON)",
    respuesta_correcta: "Peak",
    arrayRespuestas: ["Peak", "Red Bull", "Speed Max", "No hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 25,
    titulo: "Marque la presencia de las siguientes Marcas de Gaseosas (FEMSA)",
    respuesta_correcta: "Quatro",
    arrayRespuestas: ["Coca Cola", "Coca Cola Con Cafe", "Fanta", "Kola Roman", "Premio", "Quatro", "Schweppes", "Sprite", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 26,
    titulo: "Marque la presencia de las siguientes Marcas de Gaseosas (POSTOBON)",
    respuesta_correcta: "7Up",
    arrayRespuestas: ["7Up", "Bretana", "Canada Dry", "Colombiana", "Freskola", "Hipinto", "Kola", "Limonada Postobon", "Manzana Postobon", "Naranja Postobon"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 27,
    titulo: "Marque la presencia de las siguientes Marcas de Hidratante (FEMSA)",
    respuesta_correcta: "Powerade",
    arrayRespuestas: ["Powerade", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 28,
    titulo: "Marque la presencia de las siguientes Marcas de Hidratante (POSTOBON)",
    respuesta_correcta: "Gatorade",
    arrayRespuestas: ["Gatorade", "Squash", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 29,
    titulo: "Marque la presencia de las siguientes Marcas de Jugos (FEMSA)",
    respuesta_correcta: "Ades",
    arrayRespuestas: ["Ades", "Del Valle Frutal", "Del Valle Fresh"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 30,
    titulo: "Marque la presencia de las siguientes Marcas de Jugos (POSTOBON)",
    respuesta_correcta: "Hit",
    arrayRespuestas: ["Hit", "Tutti Frutti", "Tutti Frutti Citrico/Salpicon", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 31,
    titulo: "Marque la presencia de las siguientes Marcas de Maltas",
    respuesta_correcta: "Hit",
    arrayRespuestas: ["Malta Leona", "Natu Malta", "Pony Malta", "Pony Malta Vital", "Otras Marcas Maltas", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 32,
    titulo: "Marque la presencia de las siguientes Marcas de Agua: (OTRAS MARCAS)",
    respuesta_correcta: "Cielo",
    arrayRespuestas: ["Agua de Oro", "Cielo", "Condor", "Glacial", "Pool", "Saviloe", "Disfruta Aloe", "Nevada", "Vida", "Zen"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 33,
    titulo: "Marque la presencia de las siguientes Marcas de Energizante (OTRAS MARCAS)",
    respuesta_correcta: "Cielo",
    arrayRespuestas: ["Amper", "Vive 100%", "Spartan", "Energy Pool", "Full Energy Plus", "Volt", "Otras Marcas", "No hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 34,
    titulo: "Marque la presencia de las siguientes Marcas de Hidratante (OTRAS MARCAS)",
    respuesta_correcta: "Sporade",
    arrayRespuestas: ["Sporade", "Sport Mas", "Fullpower", "Hydratade Pool", "Otras Marcas", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 35,
    titulo: "Marque la presencia de las siguientes Marcas de Jugos (OTRAS MARCAS)",
    respuesta_correcta: "Cifrut",
    arrayRespuestas: ["Cifrut", "Pulp", "Fruper", "Frutto", "Sip", "Soka", "Noectar Petit", "Fruttsi", "California", "California Fesky"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 36,
    titulo: "Marque la presencia de las siguientes Marcas de Te Liquido (FEMSA)",
    respuesta_correcta: "Fuze Tea",
    arrayRespuestas: ["Fuze Tea", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 37,
    titulo: "Marque la presencia de las siguientes Marcas de Te Liquido",
    respuesta_correcta: "Cool Tea",
    arrayRespuestas: ["Cool Tea", "Otras Marcas", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 38,
    titulo: "Marque la presencia de las siguientes Marcas de Te Liquido (Postobon)",
    respuesta_correcta: "Hatsu",
    arrayRespuestas: ["Hatsu", "Lipton", "Mr Tea", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
  {
    id: 39,
    titulo: "Marque la presencia de las siguientes Marcas de Gaseosas: (OTRAS MARCAS)",
    respuesta_correcta: "Pool",
    arrayRespuestas: ["Big Cola", "Big Festival", "Big otros Sabores", "Glacial", "Frizz", "Pool", "Otras Marcas", "No Hay"],
    tipo: "multiseleccion",
    segmento: "mp",
  },
];
