// export const mexDataPhone = [
//   {
//     id: 1,
//     titulo: "¿A qué canal corresponde este punto de venta?",
//     respuesta_correcta: ["Tienda"],
//     posibles_respuestas: [
//       "Cafetería",
//       "Comida Rápida",
//       "Fonda",
//       "Tienda",
//       "Viñatería",
//     ],
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//     segmento: "punto",
//   },
//   {
//     id: 2,
//     titulo: "Qué tipo de servicio ofrece este punto de venta?",
//     respuesta_correcta: ["El cliente toma sus productos"],
//     posibles_respuestas: [
//       "El cliente toma sus productos",
//       "Opera a través de una ventanilla",
//       "Opera a través de un servicio de mesa con meseros",
//       "Otro",
//       "Ninguno",
//     ],
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//     segmento: "punto",
//   },
//   {
//     id: 3,
//     titulo:
//       "¿Cuáles de las siguientes categorías de productos se venden en este punto de venta?",
//     respuesta_correcta: [
//       "Sopas",
//       "Cigarrillos",
//       "Cerveza",
//       "Servilletas",
//       "Pedialites",
//       "Analgésicos",
//       "Remedios para el resfriado/tos",
//     ],
//     posibles_respuestas: [
//       "Alimentos para bebés",
//       "Bebidas sin alcohol listas para beber",
//       "Cerveza",
//       "Sopas",
//       "Papel higienico",
//       "Protección femenina",
//       "Cigarrillos",
//       "Servilletas",
//       "Servitoallas",
//       "Antiácidos",
//       "Pedialites",
//       "Preservativos",
//       "Analgésicos",
//       "Remedios para el resfriado/tos",
//       "Ninguna de las anteriores",
//     ],
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//     segmento: "producto",
//   },
//   {
//     id: 4,
//     titulo:
//       "¿Qué tipos de subcategorías de productos se venden en este punto de venta?",
//     respuesta_correcta: [
//       "Agua embotellada",
//       "Mantequilla",
//       "Dulces",
//       "Refrescos carbonatados",
//       " Goma de mascar",
//       "Chiles",
//       "Chocolates",
//       "Detergente para ropa",
//       "Fibras",
//       "Condimentos",
//     ],
//     posibles_respuestas: [
//       "Talco para adultos",
//       "Fórmula para bebés",
//       "Toallitas húmedas para bebés",
//       "Blanqueador",
//       "Desodorante corporal",
//       "Agua embotellada",
//       "Mantequilla",
//       "Dulces",
//       "Refrescos carbonatados",
//       "Goma de mascar",
//       "Chiles",
//       "Chocolates",
//       "Detergente para ropa",
//       "Fibras",
//       "Condimentos",
//     ],
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//     segmento: "producto",
//   },
//   {
//     id: 5,
//     titulo:
//       "¿Qué tipos de segmentos de productos se venden en este punto de venta?",
//     respuesta_correcta: [
//       "Pan empacado",
//       "Tortillas",
//       "Margarinas",
//       "Dulces",
//       "Atún",
//       "Café soluble",
//       "Crists/Chips",
//       "Bebidas Isotónicas",
//       "Bebidas Energéticas",
//       "Leche Natural",
//       "Leche Saborizada",
//       "Avena",
//       "Frijoles Secos",
//       "Puro de tomate",
//       "Aguas Saborizadas",
//       "Jugos",
//     ],
//     posibles_respuestas: [
//       "Pan empacado",
//       "Tortillas",
//       "Margarinas",
//       "Dulces",
//       "Atún",
//       "Café soluble",
//       "Harina de Maíz Precocida",
//       "Crists/Chips",
//       "Harina de Trigo",
//       "Bebidas Isotónicas",
//       "Bebidas Energéticas",
//       "Leche Natural",
//       "Leche Saborizada",
//       "Avena",
//       "Frijoles Secos",
//       "Puro de Tomate",
//       "Aguas Saborizadas",
//       "Jugos",
//     ],
//     segmento: "producto",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 6,
//     titulo: "Este establecimiento vende aguas?",
//     respuesta_correcta: ["Si"],
//     posibles_respuestas: ["Si", "No"],
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//     segmento: "enfriadores",
//   },
//   {
//     id: 7,
//     titulo: "¿Que marcas de Agua se venden en este establecimiento",
//     respuesta_correcta: ["Bonafont aguafiel"],
//     posibles_respuestas: [
//       "Canada Dry",
//       "Schweppes",
//       "Agua Pureza",
//       "Aguafiel",
//       "Aqua",
//       "Bonafont aguafiel",
//     ],
//     segmento: "enfriadores",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 8,
//     titulo: "Este establecimiento vende refrescos?",
//     respuesta_correcta: ["Si"],
//     posibles_respuestas: ["Si", "No"],
//     segmento: "enfriadores",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 9,
//     titulo: "Que marcas de Refrescos se venden en este establecimiento",
//     respuesta_correcta: ["7up", "Pepsi", "Sprite", "Squirt"],
//     posibles_respuestas: [
//       "Otros",
//       "7up",
//       "Barrilitos",
//       "Big Cola",
//       "Canada Dry",
//       "Jarritos",
//       "Lulu",
//       "Manzanita Sol",
//       "Mexicana",
//       "Mirinda",
//       "Pato Pascual",
//       "Pepsi",
//       "Red Cola",
//       "Sangria Casera",
//       "Sangria Señorial",
//       "Schweppes",
//       "Sidral Aga",
//       "Sidral Mundet",
//       "Sprite",
//       "Squirt",
//     ],
//     segmento: "enfriadores",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 10,
//     titulo: "Hay enfriadores en este punto de venta",
//     respuesta_correcta: ["Si"],
//     posibles_respuestas: ["Si", "No"],
//     segmento: "enfriadores",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 11,
//     titulo: "¿Cuantos enfriadores hay en este punto de venta?",
//     respuesta_correcta: ["2"],
//     posibles_respuestas: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
//     segmento: "enfriadores",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 12,
//     titulo: "Enfriador #1 ¿El enfriador que reportas está patrocinado?",
//     respuesta_correcta: ["Si"],
//     posibles_respuestas: ["Si", "No"],
//     segmento: "enfriador_a",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 13,
//     titulo: "¿Enfriador #1 ¿Cuantas puertas tiene este enfriador?",
//     respuesta_correcta: ["1"],
//     posibles_respuestas: ["1", "2", "3", "4", "Más de 5"],
//     segmento: "enfriador_a",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 14,
//     titulo: "Enfriador #1 ¿Que marca aparece en el enfriador?",
//     respuesta_correcta: ["Pepsi"],
//     posibles_respuestas: [
//       "Coca Cola",
//       "Jarritos",
//       "Pepsi",
//       "Red Cola",
//       "Bonafont",
//       "Peñafiel",
//       "Boing",
//       "Del Valle",
//       "Powerade",
//       "Lala",
//     ],
//     segmento: "enfriador_a",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 15,
//     titulo:
//       "Enfriador #1¿El enfriador que estás reportando está conectado a la electricidad?",
//     respuesta_correcta: ["Si"],
//     posibles_respuestas: ["Si", "No"],
//     segmento: "enfriador_a",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 16,
//     titulo:
//       "Enfriador #1 ¿En este enfriador patrocinado hay algún producto de la competencia o otros productos que no corresponden?",
//     respuesta_correcta: ["Si"],
//     posibles_respuestas: ["Si", "No"],
//     segmento: "enfriador_a",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 17,
//     titulo:
//       "Enfriador #1 ¿Cuantas caras de otros productos de la competencia y/u otros productos que no pertenecen hay en este refrigerador?",
//     respuesta_correcta: ["5 o menos"],
//     posibles_respuestas: ["5 o menos", "6 - 12", "12 - 24", "Más de 24"],
//     segmento: "enfriador_a",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 18,
//     titulo: "Enfriador #1: Toma una foto del enfriador que estas reportando",
// respuesta_correcta: [
//   "▶ Fotos legibles (No fotos al piso, no fotos borrosas, no fotos en negro, no fotos pixeladas)",
//   "▶ Tome la foto de acuerdo con el encabezado de la pregunta",
//   "▶ La foto debe mostrar la realidad del punto de venta",
//   "▶ Si la foto pertenece a un equipo de enfriamiento, debe visualizarse el equipo de enfriamiento completo.",
//   "▶ Verifique que la foto quede correctamente capturada antes de la siguiente pregunta. `",
// ],
// posibles_respuestas: [
//   "▶ Fotos legibles (No fotos al piso, no fotos borrosas, no fotos en negro, no fotos pixeladas)",
//   "▶ Tome la foto de acuerdo con el encabezado de la pregunta",
//   "▶ La foto debe mostrar la realidad del punto de venta",
//   "▶ Si la foto pertenece a un equipo de enfriamiento, debe visualizarse el equipo de enfriamiento completo.",
//   "▶ Verifique que la foto quede correctamente capturada antes de la siguiente pregunta. `",
// ],
//     segmento: "img_enfriador",
//     tipo: "foto",
//     respuestas_usuario: [],
//   },
//   {
//     id: 19,
//     titulo: "Enfriador #2 ¿El enfriador que reportas está patrocinado?",
//     respuesta_correcta: ["Si"],
//     posibles_respuestas: ["Si", "No"],
//     segmento: "enfriador_b",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 20,
//     titulo: "Enfriador #2 ¿Cuantas puertas tiene este enfriador?",
//     respuesta_correcta: ["2"],
//     posibles_respuestas: ["1", "2", "3", "4", "Más de 5"],
//     segmento: "enfriador_b",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 21,
//     titulo: "Enfriador #2 ¿Que marca aparece en el enfriador?",
//     respuesta_correcta: ["Pepsi"],
//     posibles_respuestas: [
//       "Coca Cola",
//       "Jarritos",
//       "Pepsi",
//       "Red Cola",
//       "Bonafont",
//       "Peñafiel",
//       "Boing",
//       "Del Valle",
//       "Powerade",
//       "Lala",
//     ],
//     segmento: "enfriador_b",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 22,
//     titulo:
//       "Enfriador #2 ¿El enfriador que estás reportando está conectado a la electricidad?",
//     respuesta_correcta: ["Si"],
//     posibles_respuestas: ["Si", "No"],
//     segmento: "enfriador_b",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 23,
//     titulo:
//       "Enfriador #2 ¿En este enfriador patrocinado hay algún producto de la competencia o otros productos que no corresponden?",
//     respuesta_correcta: ["Si"],
//     posibles_respuestas: ["Si", "No"],
//     segmento: "enfriador_b",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 24,
//     titulo:
//       "Enfriador #2 ¿Cuantas caras de otros productos de la competencia y/u otros productos que no pertenecen hay en este refrigerador?",
//     respuesta_correcta: ["5 o menos"],
//     posibles_respuestas: ["5 o menos", "6 - 12", "12 - 24", "Más de 24"],
//     segmento: "enfriador_b",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 25,
//     titulo: "Enfriador #2: Toma una foto del enfriador que estas reportando",
// respuesta_correcta: [
//   "▶ Fotos legibles (No fotos al piso, no fotos borrosas, no fotos en negro, no fotos pixeladas)",
//   "▶ Tome la foto de acuerdo con el encabezado de la pregunta",
//   "▶ La foto debe mostrar la realidad del punto de venta",
//   "▶ Si la foto pertenece a un equipo de enfriamiento, debe visualizarse el equipo de enfriamiento completo.",
//   "▶ Verifique que la foto quede correctamente capturada antes de la siguiente pregunta. `",
// ],
// posibles_respuestas: [
//   "▶ Fotos legibles (No fotos al piso, no fotos borrosas, no fotos en negro, no fotos pixeladas)",
//   "▶ Tome la foto de acuerdo con el encabezado de la pregunta",
//   "▶ La foto debe mostrar la realidad del punto de venta",
//   "▶ Si la foto pertenece a un equipo de enfriamiento, debe visualizarse el equipo de enfriamiento completo.",
//   "▶ Verifique que la foto quede correctamente capturada antes de la siguiente pregunta. `",
// ],
//     segmento: "imgPepsi",
//     tipo: "foto",
//     respuestas_usuario: [],
//   },
//   {
//     id: 26,
//     titulo: "Este punto de venta vende Detergente para Ropa en los estantes?",
//     respuesta_correcta: ["No"],
//     posibles_respuestas: ["Si", "No"],
//     segmento: "detergentes",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 27,
//     titulo:
//       "Pregunta al encargado del establecimiento: ¿Vende detergente para la ropa?",
//     respuesta_correcta: ["Si"],
//     posibles_respuestas: ["Si", "No"],
//     segmento: "detergentes",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 28,
//     titulo:
//       "¿Que marcas de detergente para ropa se venden en este punto de venta?",
//     respuesta_correcta: ["Roma", "Ariel", "Ace", "Salvo Multisos"],
//     posibles_respuestas: [
//       "Vide",
//       "Arm & Hammer",
//       "Vel Rosita",
//       "Blanca Nieves",
//       "Carisma",
//       "Persil",
//       "Viva",
//       "Pinol",
//       "Xpress",
//       "Ace",
//       "Ariel",
//       "Salvo Multisos",
//       "Doña Blanca",
//       "Foca",
//       "Puro Sol",
//       "Roma",
//       "Tepeyac",
//       "1.2.3",
//       "Mas",
//     ],
//     segmento: "detergentes",
//     tipo: "multiseleccion",
//     respuestas_usuario: [],
//   },
//   {
//     id: 29,
//     titulo: "Toma una foto de la secciòn de productos de limpieza.",
// respuesta_correcta: [
//   "▶ Fotos legibles (No fotos al piso, no fotos borrosas, no fotos en negro, no fotos pixeladas)",
//   "▶ Tome la foto de acuerdo con el encabezado de la pregunta",
//   "▶ La foto debe mostrar la realidad del punto de venta",
//   "▶ Si la foto pertenece a un equipo de enfriamiento, debe visualizarse el equipo de enfriamiento completo.",
//   "▶ Verifique que la foto quede correctamente capturada antes de la siguiente pregunta. `",
// ],
// posibles_respuestas: [
//   "▶ Fotos legibles (No fotos al piso, no fotos borrosas, no fotos en negro, no fotos pixeladas)",
//   "▶ Tome la foto de acuerdo con el encabezado de la pregunta",
//   "▶ La foto debe mostrar la realidad del punto de venta",
//   "▶ Si la foto pertenece a un equipo de enfriamiento, debe visualizarse el equipo de enfriamiento completo.",
//   "▶ Verifique que la foto quede correctamente capturada antes de la siguiente pregunta. `",
// ],
//     segmento: "imgDetergente",
//     tipo: "foto",
//     respuestas_usuario: [],
//   },
// ];

export const mexDataPhone = [
  {
    id: 1,
    titulo: "¿A qué canal corresponde este punto de venta?",
    respuesta_correcta: ["Tienda"],
    posibles_respuestas: [
      "Cafetería",
      "Comida Rápida",
      "Fonda",
      "Tienda",
      "Viñatería",
    ],
    tipo: "multiseleccion",
    respuestas_usuario: ["Tienda"],
    segmento: "punto",
  },
  {
    id: 2,
    titulo: "Qué tipo de servicio ofrece este punto de venta?",
    respuesta_correcta: ["El cliente toma sus productos"],
    posibles_respuestas: [
      "El cliente toma sus productos",
      "Opera a través de una ventanilla",
      "Opera a través de un servicio de mesa con meseros",
      "Otro",
      "Ninguno",
    ],
    tipo: "multiseleccion",
    respuestas_usuario: ["El cliente toma sus productos"],
    segmento: "punto",
  },
  {
    id: 3,
    titulo:
      "¿Cuáles de las siguientes categorías de productos se venden en este punto de venta?",
    respuesta_correcta: [
      "Sopas",
      "Cigarrillos",
      "Cerveza",
      "Servilletas",
      "Pedialites",
      "Analgésicos",
      "Remedios para el resfriado/tos",
    ],
    posibles_respuestas: [
      "Alimentos para bebés",
      "Bebidas sin alcohol listas para beber",
      "Cerveza",
      "Sopas",
      "Papel higienico",
      "Protección femenina",
      "Cigarrillos",
      "Servilletas",
      "Servitoallas",
      "Antiácidos",
      "Pedialites",
      "Preservativos",
      "Analgésicos",
      "Remedios para el resfriado/tos",
      "Ninguna de las anteriores",
    ],
    tipo: "multiseleccion",
    respuestas_usuario: [
      "Sopas",
      "Cigarrillos",
      "Cerveza",
      "Servilletas",
      "Pedialites",
      "Analgésicos",
      "Remedios para el resfriado/tos",
    ],
    segmento: "producto",
  },
  {
    id: 4,
    titulo:
      "¿Qué tipos de subcategorías de productos se venden en este punto de venta?",
    respuesta_correcta: [
      "Agua embotellada",
      "Mantequilla",
      "Dulces",
      "Refrescos carbonatados",
      " Goma de mascar",
      "Chiles",
      "Chocolates",
      "Detergente para ropa",
      "Fibras",
      "Condimentos",
    ],
    posibles_respuestas: [
      "Talco para adultos",
      "Fórmula para bebés",
      "Toallitas húmedas para bebés",
      "Blanqueador",
      "Desodorante corporal",
      "Agua embotellada",
      "Mantequilla",
      "Dulces",
      "Refrescos carbonatados",
      "Goma de mascar",
      "Chiles",
      "Chocolates",
      "Detergente para ropa",
      "Fibras",
      "Condimentos",
    ],
    tipo: "multiseleccion",
    respuestas_usuario: [
      "Agua embotellada",
      "Mantequilla",
      "Dulces",
      "Refrescos carbonatados",
      " Goma de mascar",
      "Chiles",
      "Chocolates",
      "Detergente para ropa",
      "Fibras",
      "Condimentos",
    ],
    segmento: "producto",
  },
  {
    id: 5,
    titulo:
      "¿Qué tipos de segmentos de productos se venden en este punto de venta?",
    respuesta_correcta: [
      "Pan empacado",
      "Tortillas",
      "Margarinas",
      "Dulces",
      "Atún",
      "Café soluble",
      "Crists/Chips",
      "Bebidas Isotónicas",
      "Bebidas Energéticas",
      "Leche Natural",
      "Leche Saborizada",
      "Avena",
      "Frijoles Secos",
      "Puro de tomate",
      "Aguas Saborizadas",
      "Jugos",
    ],
    posibles_respuestas: [
      "Pan empacado",
      "Tortillas",
      "Margarinas",
      "Dulces",
      "Atún",
      "Café soluble",
      "Harina de Maíz Precocida",
      "Crists/Chips",
      "Harina de Trigo",
      "Bebidas Isotónicas",
      "Bebidas Energéticas",
      "Leche Natural",
      "Leche Saborizada",
      "Avena",
      "Frijoles Secos",
      "Puro de Tomate",
      "Aguas Saborizadas",
      "Jugos",
    ],
    segmento: "producto",
    tipo: "multiseleccion",
    respuestas_usuario: [
      "Pan empacado",
      "Tortillas",
      "Margarinas",
      "Dulces",
      "Atún",
      "Café soluble",
      "Crists/Chips",
      "Bebidas Isotónicas",
      "Bebidas Energéticas",
      "Leche Natural",
      "Leche Saborizada",
      "Avena",
      "Frijoles Secos",
      "Puro de tomate",
      "Aguas Saborizadas",
      "Jugos",
    ],
  },
  {
    id: 6,
    titulo: "Este establecimiento vende aguas?",
    respuesta_correcta: ["Si"],
    posibles_respuestas: ["Si", "No"],
    tipo: "multiseleccion",
    respuestas_usuario: ["Si"],
    segmento: "enfriadores",
  },
  {
    id: 7,
    titulo: "¿Que marcas de Agua se venden en este establecimiento",
    respuesta_correcta: ["Bonafont aguafiel"],
    posibles_respuestas: [
      "Canada Dry",
      "Schweppes",
      "Agua Pureza",
      "Aguafiel",
      "Aqua",
      "Bonafont aguafiel",
    ],
    segmento: "enfriadores",
    tipo: "multiseleccion",
    respuestas_usuario: ["Bonafont aguafiel"],
  },
  {
    id: 8,
    titulo: "Este establecimiento vende refrescos?",
    respuesta_correcta: ["Si"],
    posibles_respuestas: ["Si", "No"],
    segmento: "enfriadores",
    tipo: "multiseleccion",
    respuestas_usuario: ["Si"],
  },
  {
    id: 9,
    titulo: "Que marcas de Refrescos se venden en este establecimiento",
    respuesta_correcta: ["7up", "Pepsi", "Sprite", "Squirt"],
    posibles_respuestas: [
      "Otros",
      "7up",
      "Barrilitos",
      "Big Cola",
      "Canada Dry",
      "Jarritos",
      "Lulu",
      "Manzanita Sol",
      "Mexicana",
      "Mirinda",
      "Pato Pascual",
      "Pepsi",
      "Red Cola",
      "Sangria Casera",
      "Sangria Señorial",
      "Schweppes",
      "Sidral Aga",
      "Sidral Mundet",
      "Sprite",
      "Squirt",
    ],
    segmento: "enfriadores",
    tipo: "multiseleccion",
    respuestas_usuario: ["7up", "Pepsi", "Sprite", "Squirt"],
  },
  {
    id: 10,
    titulo: "Hay enfriadores en este punto de venta",
    respuesta_correcta: ["Si"],
    posibles_respuestas: ["Si", "No"],
    segmento: "enfriadores",
    tipo: "multiseleccion",
    respuestas_usuario: ["Si"],
  },
  {
    id: 11,
    titulo: "¿Cuantos enfriadores hay en este punto de venta?",
    respuesta_correcta: ["2"],
    posibles_respuestas: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    segmento: "enfriadores",
    tipo: "multiseleccion",
    respuestas_usuario: ["2"],
  },
  {
    id: 12,
    titulo: "Enfriador #1 ¿El enfriador que reportas está patrocinado?",
    respuesta_correcta: ["Si"],
    posibles_respuestas: ["Si", "No"],
    segmento: "enfriador_a",
    tipo: "multiseleccion",
    respuestas_usuario: ["Si"],
  },
  {
    id: 13,
    titulo: "¿Enfriador #1 ¿Cuantas puertas tiene este enfriador?",
    respuesta_correcta: ["1"],
    posibles_respuestas: ["1", "2", "3", "4", "Más de 5"],
    segmento: "enfriador_a",
    tipo: "multiseleccion",
    respuestas_usuario: ["1"],
  },
  {
    id: 14,
    titulo: "Enfriador #1 ¿Que marca aparece en el enfriador?",
    respuesta_correcta: ["Pepsi"],
    posibles_respuestas: [
      "Coca Cola",
      "Jarritos",
      "Pepsi",
      "Red Cola",
      "Bonafont",
      "Peñafiel",
      "Boing",
      "Del Valle",
      "Powerade",
      "Lala",
    ],
    segmento: "enfriador_a",
    tipo: "multiseleccion",
    respuestas_usuario: ["Pepsi"],
  },
  {
    id: 15,
    titulo:
      "Enfriador #1¿El enfriador que estás reportando está conectado a la electricidad?",
    respuesta_correcta: ["Si"],
    posibles_respuestas: ["Si", "No"],
    segmento: "enfriador_a",
    tipo: "multiseleccion",
    respuestas_usuario: ["Si"],
  },
  {
    id: 16,
    titulo:
      "Enfriador #1 ¿En este enfriador patrocinado hay algún producto de la competencia o otros productos que no corresponden?",
    respuesta_correcta: ["Si"],
    posibles_respuestas: ["Si", "No"],
    segmento: "enfriador_a",
    tipo: "multiseleccion",
    respuestas_usuario: ["Si"],
  },
  {
    id: 17,
    titulo:
      "Enfriador #1 ¿Cuantas caras de otros productos de la competencia y/u otros productos que no pertenecen hay en este refrigerador?",
    respuesta_correcta: ["5 o menos"],
    posibles_respuestas: ["5 o menos", "6 - 12", "12 - 24", "Más de 24"],
    segmento: "enfriador_a",
    tipo: "multiseleccion",
    respuestas_usuario: ["5 o menos"],
  },
  {
    id: 18,
    titulo: "Enfriador #1: Toma una foto del enfriador que estas reportando",
    respuesta_correcta: [
      "▶ Fotos legibles (No fotos al piso, no fotos borrosas, no fotos en negro, no fotos pixeladas)",
      "▶ Tome la foto de acuerdo con el encabezado de la pregunta",
      "▶ La foto debe mostrar la realidad del punto de venta",
      "▶ Si la foto pertenece a un equipo de enfriamiento, debe visualizarse el equipo de enfriamiento completo.",
      "▶ Verifique que la foto quede correctamente capturada antes de la siguiente pregunta. `",
    ],
    posibles_respuestas: [
      "▶ Fotos legibles (No fotos al piso, no fotos borrosas, no fotos en negro, no fotos pixeladas)",
      "▶ Tome la foto de acuerdo con el encabezado de la pregunta",
      "▶ La foto debe mostrar la realidad del punto de venta",
      "▶ Si la foto pertenece a un equipo de enfriamiento, debe visualizarse el equipo de enfriamiento completo.",
      "▶ Verifique que la foto quede correctamente capturada antes de la siguiente pregunta. `",
    ],
    segmento: "img_enfriador",
    namePhoto: "mexImgDetergentes",
    tipo: "foto",
    respuestas_usuario: [
      "▶ Tome la foto de acuerdo con el encabezado de la pregunta",
    ],
  },
  {
    id: 19,
    titulo: "Enfriador #2 ¿El enfriador que reportas está patrocinado?",
    respuesta_correcta: ["Si"],
    posibles_respuestas: ["Si", "No"],
    segmento: "enfriador_b",
    tipo: "multiseleccion",
    respuestas_usuario: ["Si"],
  },
  {
    id: 20,
    titulo: "Enfriador #2 ¿Cuantas puertas tiene este enfriador?",
    respuesta_correcta: ["2"],
    posibles_respuestas: ["1", "2", "3", "4", "Más de 5"],
    segmento: "enfriador_b",
    tipo: "multiseleccion",
    respuestas_usuario: ["2"],
  },
  {
    id: 21,
    titulo: "Enfriador #2 ¿Que marca aparece en el enfriador?",
    respuesta_correcta: ["Pepsi"],
    posibles_respuestas: [
      "Coca Cola",
      "Jarritos",
      "Pepsi",
      "Red Cola",
      "Bonafont",
      "Peñafiel",
      "Boing",
      "Del Valle",
      "Powerade",
      "Lala",
    ],
    segmento: "enfriador_b",
    tipo: "multiseleccion",
    respuestas_usuario: ["Pepsi"],
  },
  {
    id: 22,
    titulo:
      "Enfriador #2 ¿El enfriador que estás reportando está conectado a la electricidad?",
    respuesta_correcta: ["Si"],
    posibles_respuestas: ["Si", "No"],
    segmento: "enfriador_b",
    tipo: "multiseleccion",
    respuestas_usuario: ["Si"],
  },
  {
    id: 23,
    titulo:
      "Enfriador #2 ¿En este enfriador patrocinado hay algún producto de la competencia o otros productos que no corresponden?",
    respuesta_correcta: ["Si"],
    posibles_respuestas: ["Si", "No"],
    segmento: "enfriador_b",
    tipo: "multiseleccion",
    respuestas_usuario: ["Si"],
  },
  {
    id: 24,
    titulo:
      "Enfriador #2 ¿Cuantas caras de otros productos de la competencia y/u otros productos que no pertenecen hay en este refrigerador?",
    respuesta_correcta: ["5 o menos"],
    posibles_respuestas: ["5 o menos", "6 - 12", "12 - 24", "Más de 24"],
    segmento: "enfriador_b",
    tipo: "multiseleccion",
    respuestas_usuario: ["5 o menos"],
  },
  {
    id: 25,
    titulo: "Enfriador #2: Toma una foto del enfriador que estas reportando",
    respuesta_correcta: [
      "▶ Fotos legibles (No fotos al piso, no fotos borrosas, no fotos en negro, no fotos pixeladas)",
      "▶ Tome la foto de acuerdo con el encabezado de la pregunta",
      "▶ La foto debe mostrar la realidad del punto de venta",
      "▶ Si la foto pertenece a un equipo de enfriamiento, debe visualizarse el equipo de enfriamiento completo.",
      "▶ Verifique que la foto quede correctamente capturada antes de la siguiente pregunta. `",
    ],
    posibles_respuestas: [
      "▶ Fotos legibles (No fotos al piso, no fotos borrosas, no fotos en negro, no fotos pixeladas)",
      "▶ Tome la foto de acuerdo con el encabezado de la pregunta",
      "▶ La foto debe mostrar la realidad del punto de venta",
      "▶ Si la foto pertenece a un equipo de enfriamiento, debe visualizarse el equipo de enfriamiento completo.",
      "▶ Verifique que la foto quede correctamente capturada antes de la siguiente pregunta. `",
    ],
    segmento: "imgPepsi",
    namePhoto: "mexImgPepsi",
    tipo: "foto",
    respuestas_usuario: ["imgPepsi"],
  },
  {
    id: 26,
    titulo: "Este punto de venta vende Detergente para Ropa en los estantes?",
    respuesta_correcta: ["No"],
    posibles_respuestas: ["Si", "No"],
    segmento: "detergentes",
    tipo: "multiseleccion",
    respuestas_usuario: ["No"],
  },
  {
    id: 27,
    titulo:
      "Pregunta al encargado del establecimiento: ¿Vende detergente para la ropa?",
    respuesta_correcta: ["Si"],
    posibles_respuestas: ["Si", "No"],
    segmento: "detergentes",
    tipo: "multiseleccion",
    respuestas_usuario: ["Si"],
  },
  {
    id: 28,
    titulo:
      "¿Que marcas de detergente para ropa se venden en este punto de venta?",
    respuesta_correcta: ["Roma", "Ariel", "Ace", "Salvo Multisos"],
    posibles_respuestas: [
      "Vide",
      "Arm & Hammer",
      "Vel Rosita",
      "Blanca Nieves",
      "Carisma",
      "Persil",
      "Viva",
      "Pinol",
      "Xpress",
      "Ace",
      "Ariel",
      "Salvo Multisos",
      "Doña Blanca",
      "Foca",
      "Puro Sol",
      "Roma",
      "Tepeyac",
      "1.2.3",
      "Mas",
    ],
    segmento: "detergentes",
    tipo: "multiseleccion",
    respuestas_usuario: ["Roma", "Ariel", "Ace", "Salvo Multisos"],
  },
  {
    id: 29,
    titulo:
      "Toma una foto de la secciòn de productos de limpieza como se muestra en el ejemplo:",
    respuesta_correcta: [
      "▶ Fotos legibles (No fotos al piso, no fotos borrosas, no fotos en negro, no fotos pixeladas)",
      "▶ Tome la foto de acuerdo con el encabezado de la pregunta",
      "▶ La foto debe mostrar la realidad del punto de venta",
      "▶ Si la foto pertenece a un equipo de enfriamiento, debe visualizarse el equipo de enfriamiento completo.",
      "▶ Verifique que la foto quede correctamente capturada antes de la siguiente pregunta. `",
    ],
    posibles_respuestas: [
      "▶ Fotos legibles (No fotos al piso, no fotos borrosas, no fotos en negro, no fotos pixeladas)",
      "▶ Tome la foto de acuerdo con el encabezado de la pregunta",
      "▶ La foto debe mostrar la realidad del punto de venta",
      "▶ Si la foto pertenece a un equipo de enfriamiento, debe visualizarse el equipo de enfriamiento completo.",
      "▶ Verifique que la foto quede correctamente capturada antes de la siguiente pregunta. `",
    ],
    segmento: "imgDetergente",
    namePhoto: "mexImgDetergentes",
    tipo: "foto",
    respuestas_usuario: ["imgDetergente"],
  },
];
